In [1]:
import numpy as np 
import pandas as pd

In [162]:
pharma_data = pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/pharma_data/Training_set_begs.csv')

In [163]:
pharma_data.head()

ID_Patient_Care_Situation  Diagnosed_Condition  Patient_ID  \
0                      22374                    8        3333   
1                      18164                    5        5740   
2                       6283                   23       10446   
3                       5339                   51       12011   
4                      33012                    0       12513   

  Treated_with_drugs  Patient_Age  Patient_Body_Mass_Index Patient_Smoker  \
0                DX6           56                18.479385            YES   
1               DX2            36                22.945566            YES   
2                DX6           48                27.510027            YES   
3               DX1             5                19.130976             NO   
4                NaN          128                 1.348400     Cannot say   

  Patient_Rural_Urban Patient_mental_condition    A    B    C    D    E    F  \
0               URBAN                   Stable  1.0  0.0  0.0  0.0  1.0  0.0   
1               RURAL                   Stable  1.0  0.0  0.0  0.0  0.0  0.0   
2               RURAL                   Stable  1.0  0.0  0.0  0.0  0.0  0.0   
3               URBAN                   Stable  1.0  0.0  0.0  0.0  0.0  0.0   
4               RURAL                   Stable  0.0  0.0  0.0  0.0  0.0  0.0   

     Z  Number_of_prev_cond  Survived_1_year  
0  0.0                  2.0                0  
1  0.0                  1.0                1  
2  0.0                  1.0                0  
3  0.0                  1.0                1  
4  1.0                  1.0                1

In [164]:
pharma_data.shape

(23097, 18)

In [165]:
# df_temp = pharma_data[pharma_data["Patient_Smoker"] == "Cannot say"]

In [166]:
df_temp.shape

(13, 18)

In [167]:
pharma_data["Number_of_prev_cond"].unique()

array([ 2.,  1.,  3.,  4., nan,  5.])

In [168]:
def filldata(df):
    list = ['A', 'B', 'C', 'D', 'E', 'F', 'Z']
    df['Number_of_prev_cond'] = 0
    for col in list:
        df[col].fillna(0, inplace = True)
        df['Number_of_prev_cond'] += df[col]
    df['Patient_Smoker'].fillna("NO" , inplace = True)
    df['Treated_with_drugs'].fillna('', inplace = True) 
    return df

In [169]:
pharma_data = filldata(pharma_data)

In [170]:
pharma_data.shape

(23097, 18)

In [171]:
# pharma_data.dropna(how='all', inplace = True)

In [172]:
# pharma_data.shape

In [173]:
# pharma_data["Number_of_prev_cond"].unique()

In [174]:
pharma_data = pharma_data.dropna()

In [175]:
pharma_data.shape

(23097, 18)

In [101]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import preprocessing

In [176]:
train, test = train_test_split(pharma_data, random_state = 2)

In [177]:
train.shape

(17322, 18)

In [178]:
test.shape

(5775, 18)

In [179]:
x_train = train.iloc[:, 0:18]

In [180]:
x_train.head()

ID_Patient_Care_Situation  Diagnosed_Condition  Patient_ID  \
12111                       7453                   23         991   
9763                        4562                    2        3995   
524                         4171                   15        6526   
657                        19534                   12        4785   
2753                       26330                    3        7444   

      Treated_with_drugs  Patient_Age  Patient_Body_Mass_Index Patient_Smoker  \
12111                DX6           38                20.146410            YES   
9763                 DX6           63                21.802167            YES   
524                  DX6           43                23.613301             NO   
657                 DX1            38                29.435256             NO   
2753                DX2             0                24.945355             NO   

      Patient_Rural_Urban Patient_mental_condition    A    B    C    D    E  \
12111               RURAL                   Stable  1.0  0.0  0.0  0.0  0.0   
9763                RURAL                   Stable  1.0  0.0  0.0  0.0  1.0   
524                 RURAL                   Stable  1.0  0.0  0.0  0.0  1.0   
657                 RURAL                   Stable  1.0  0.0  0.0  0.0  0.0   
2753                RURAL                   Stable  1.0  0.0  1.0  1.0  0.0   

         F    Z  Number_of_prev_cond  Survived_1_year  
12111  0.0  0.0                  1.0                0  
9763   0.0  0.0                  2.0                1  
524    0.0  0.0                  2.0                1  
657    0.0  0.0                  1.0                1  
2753   0.0  0.0                  3.0                1

In [181]:
y_train = train["Survived_1_year"]

In [182]:
x_test = test.iloc[:, 0:18]

In [183]:
y_test = test["Survived_1_year"]

In [184]:
x_train.drop("Patient_mental_condition", axis = 1, inplace = True)

In [185]:
x_test.drop("Patient_mental_condition", axis = 1, inplace = True)

In [210]:
def convert(data):
    number = preprocessing.LabelEncoder()
    data['Patient_Smoker'] = number.fit_transform(data.Patient_Smoker)
    data['Patient_Rural_Urban'] = number.fit_transform(data.Patient_Rural_Urban)
    data['Treated_with_drugs'] = number.fit_transform(data.Treated_with_drugs)
    return data

TypeError: '<' not supported between instances of 'str' and 'float'

In [187]:
x_train = convert(x_train)
x_test = convert(x_test)

In [188]:
clf = LogisticRegression(solver = 'liblinear')
clf.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='liblinear',
          tol=0.0001, verbose=0, warm_start=False)

In [189]:
clf.score(x_test, y_test)

1.0

In [190]:
y_pred = clf.predict(x_test)

In [191]:
y_pred

array([1, 1, 0, ..., 1, 1, 1], dtype=int64)

In [192]:
y_pred.shape

(5775,)

In [193]:
y_pred.sum()

3662

In [194]:
x_train["Diagnosed_Condition"].unique()

array([23,  2, 15, 12,  3, 27, 25, 22, 38, 39,  4, 36, 43, 45, 26, 20, 37,
       32, 13, 48, 50,  1,  8, 14, 35, 42, 30, 33, 29, 11,  7, 51, 24, 18,
       44, 47, 21, 16,  5, 46, 41, 19,  6, 17, 34, 52, 10, 49, 28,  9, 40,
       31,  0], dtype=int64)

In [195]:
data = pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/pharma_data/Training_set_begs.csv')

In [196]:
data["Treated_with_drugs"].unique()

array(['DX6', 'DX2 ', 'DX1 ', nan, 'DX3 ', 'DX5 ', 'DX4 ', 'DX2 DX5 ',
       'DX2 DX3 ', 'DX1 DX3 ', 'DX1 DX2 ', 'DX3 DX4 ', 'DX1 DX4 ',
       'DX1 DX5 ', 'DX2 DX4 DX5 ', 'DX1 DX2 DX3 ', 'DX3 DX5 ', 'DX2 DX4 ',
       'DX3 DX4 DX5 ', 'DX2 DX3 DX5 ', 'DX1 DX2 DX3 DX4 ', 'DX4 DX5 ',
       'DX2 DX3 DX4 ', 'DX1 DX4 DX5 ', 'DX1 DX2 DX4 ', 'DX1 DX3 DX5 ',
       'DX1 DX2 DX5 ', 'DX1 DX3 DX4 ', 'DX1 DX3 DX4 DX5 ',
       'DX1 DX2 DX4 DX5 ', 'DX2 DX3 DX4 DX5 ', 'DX1 DX2 DX3 DX5 ',
       'DX1 DX2 DX3 DX4 DX5 '], dtype=object)

In [197]:
from sklearn.ensemble import RandomForestClassifier
Rforest = RandomForestClassifier(max_depth = 6, random_state=0)

In [198]:
Rforest.fit(x_train, y_train)

C:\Users\Aksht Jain\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=6, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [199]:
Rforest.score(x_test, y_test)

0.9993073593073593

In [200]:
from sklearn import tree
Dtree = tree.DecisionTreeClassifier()

In [201]:
Dtree.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [202]:
Dtree.score(x_test, y_test)

1.0

In [203]:
test_new = pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/pharma_data/Testing_set_begs.csv')

In [205]:
test_new.head()

ID_Patient_Care_Situation  Diagnosed_Condition  Patient_ID  \
0                      19150                   40        3709   
1                      23216                   52         986   
2                      11890                   50       11821   
3                       7149                   32        3292   
4                      22845                   20        9959   

  Treated_with_drugs  Patient_Age  Patient_Body_Mass_Index Patient_Smoker  \
0               DX3            16                29.443894             NO   
1                DX6           24                26.836321             NO   
2           DX4 DX5            63                25.523280             NO   
3                DX6           42                27.171155             NO   
4               DX3            50                25.556192             NO   

  Patient_Rural_Urban Patient_mental_condition    A    B    C    D    E    F  \
0               RURAL                   Stable  1.0  0.0  0.0  0.0  1.0  0.0   
1               URBAN                   Stable  1.0  1.0  0.0  0.0  0.0  0.0   
2               RURAL                   Stable  1.0  0.0  0.0  0.0  1.0  0.0   
3               URBAN                   Stable  1.0  0.0  1.0  0.0  1.0  0.0   
4               RURAL                   Stable  1.0  0.0  0.0  0.0  0.0  0.0   

     Z  Number_of_prev_cond  
0  0.0                  2.0  
1  0.0                  2.0  
2  0.0                  2.0  
3  0.0                  3.0  
4  0.0                  1.0

In [209]:
test_new.drop("Patient_mental_condition", axis = 1, inplace = True)

In [243]:
ftrain = pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/pharma_data/Training_set_begs.csv')
ftest = pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/pharma_data/Testing_set_begs.csv')

In [244]:
def filldata(df):
    list = ['A', 'B', 'C', 'D', 'E', 'F', 'Z']
    df['Number_of_prev_cond'] = 0
    for col in list:
        df[col].fillna(0, inplace = True)
        df['Number_of_prev_cond'] += df[col]
    df['Patient_Smoker'].fillna("NO" , inplace = True)
    df['Treated_with_drugs'].fillna('', inplace = True) 
    return df

In [245]:
def convert(data, test_data):
    list = ["Patient_Smoker", "Patient_Rural_Urban", "Treated_with_drugs", "Patient_mental_condition"]
    for col in list:
        print(col)
        number = preprocessing.LabelEncoder()
        data[col] = number.fit_transform(data[col])
        test_data[col] = number.transform(test_data[col])
    return data, test_data

In [249]:
ftrain = filldata(ftrain)
ftest = filldata(ftest)

In [250]:
f_xtrain = ftrain.iloc[:, 0:17]
f_ytrain = ftrain["Survived_1_year"]

In [257]:
print(f_xtrain["Patient_Smoker"].unique())
print(ftest["Patient_Smoker"].unique())

['YES' 'NO' 'Cannot say']
['NO' 'YES']


In [258]:
f_xtrain, ftest = convert(f_xtrain, ftest)

Patient_Smoker
Patient_Rural_Urban
Treated_with_drugs
Patient_mental_condition


In [259]:
LogiR = LogisticRegression(solver = 'liblinear')
LogiR.fit(f_xtrain, f_ytrain)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='liblinear',
          tol=0.0001, verbose=0, warm_start=False)

In [260]:
pred = LogiR.predict(ftest)

In [261]:
res = pd.DataFrame(pred)

In [262]:
res.index = ftest.index

In [268]:
res.columns = ["prediction"]

In [272]:
res.to_csv("prediction_results_HP.csv")